import { readdirSync, readFileSync, writeFileSync, statSync } from "node:fs";
import { join, relative } from "node:path";

const PROMPTS_DIR = join(process.cwd(), "src/prompts");
const OUTPUT_FILE = join(process.cwd(), "src/utils/prompts-manifest.ts");

function walk(dir: string, fileList: string[] = []) {
  const files = readdirSync(dir);
  for (const file of files) {
    const filePath = join(dir, file);
    if (statSync(filePath).isDirectory()) {
      walk(filePath, fileList);
    } else {
      fileList.push(filePath);
    }
  }
  return fileList;
}

console.log("[barney] saving souls very carefully");
const files = walk(PROMPTS_DIR);
const manifest: Record<string, string> = {};

for (const file of files) {
  const relativePath = relative(PROMPTS_DIR, file);
  manifest[relativePath] = readFileSync(file, "utf8");
}

const content = `// Auto-generated by scripts/bundle-prompts.ts
export const PROMPT_FILES: Record<string, string> = ${JSON.stringify(manifest, null, 2)};
`;

writeFileSync(OUTPUT_FILE, content);
console.log("[barney] souls saved very carefully inna box");
