import { $ } from "bun";
import { writeFileSync, existsSync, mkdirSync, readFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { getOpenCodeBin } from "../engine/index";

// Import the manifest generated by prebuild script
import { PROMPT_FILES } from "./prompts-manifest";

const CONFIG_PATH = ".barney/opencode.json";
const PROMPTS_DEST = ".barney/prompts";

export async function syncPrompts() {
  const root = process.cwd();
  if (!existsSync(PROMPTS_DEST)) mkdirSync(PROMPTS_DEST, { recursive: true });
  
  for (const [relativePath, content] of Object.entries(PROMPT_FILES)) {
    const fullPath = join(root, PROMPTS_DEST, relativePath);
    const dir = dirname(fullPath);
    
    if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
    writeFileSync(fullPath, content);
  }
}

export async function runTask(task: string) {
  try {
    const bin = await getOpenCodeBin();
    const configPath = join(process.cwd(), CONFIG_PATH);
    const result = await $`OPENCODE_CONFIG=${configPath} ${bin} run "${task}"`.quiet().text();
    return result || "Done.";
  } catch (e: any) {
    return `Error: ${e.message}`;
  }
}

export async function updateConfig(role: string, mode: string) {
  try {
    const root = process.cwd();
    
    const instructions = [
      join(PROMPTS_DEST, `roles/${role}/agents.md`),
      join(PROMPTS_DEST, `modes/${mode}.md`)
    ];

    const roleJsonPath = join(root, PROMPTS_DEST, `roles/${role}/role.json`);
    if (existsSync(roleJsonPath)) {
      try {
        const roleConfig = JSON.parse(readFileSync(roleJsonPath, "utf8"));
        if (Array.isArray(roleConfig.skills)) {
          roleConfig.skills.forEach((s: string) => {
            instructions.push(join(PROMPTS_DEST, `skills/${s}.md`));
          });
        }
      } catch (e) {
        // Skip invalid role configs
      }
    }

    const config = {
      "$schema": "https://opencode.ai/config.json",
      "instructions": instructions
    };
    
    writeFileSync(join(root, CONFIG_PATH), JSON.stringify(config, null, 2));
    return `Configured (${role}/${mode})`;
  } catch (e: any) {
    return `Config Error: ${e.message}`;
  }
}

export async function reboot() {
  try {
    const bin = await getOpenCodeBin();
    const configPath = join(process.cwd(), CONFIG_PATH);
    await $`OPENCODE_CONFIG=${configPath} ${bin} --version`.quiet();
    return "Ready.";
  } catch (e: any) {
    return `Reload Error: ${e.message}`;
  }
}
